name: allCov
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  odbTest:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 1-testDb
          MYSQL_DATABASE: heratestdb
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - name: Baseline for later scripted manual setup of go1.20
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.14
    - name: allCovSh
      run: tests/unittest/allcover.sh
    - uses: actions/upload-artifact@v4
      with:
        name: coverage web page
        path: /home/runner/go/allcover.htm
