name: Manual functionaltest
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  funcTest:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 1-testDb
          MYSQL_DATABASE: heratestdb
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: System Test
      run: tests/functionaltest/runall.sh
